version: '3.9'

services:
  db:
    image: mysql:5.7
    ports:
      - 3306:3306
    volumes:
      - jobx_matcher:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: true
      MYSQL_DATABASE: jobx_matcher

volumes:
  jobx_matcher: {}
