name: Deploy to prod

on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploying to prod
    runs-on: ubuntu-latest

    steps:
      - name: Cloning repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Push to production
        uses: dokku/github-action@master
        with:
          git_remote_url: ${{ secrets.SSH_REMOTE_DEPLOY }}
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
